### ISSUE TITLE
segfault after opening rom

### ISSUE THREAD

**Issue by ddevault** [alberthdev/wxwabbitemu#1] opened 2014-11-15 22:11 UTC
```
sircmpwn@homura /t/t/wxwabbitemu master> gdb ./bin/wxWabbitemu 
GNU gdb (GDB) 7.8.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/wxWabbitemu...done.
(gdb) run
Starting program: /tmp/tmp.HmTOKNiunI/wxwabbitemu/bin/wxWabbitemu 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffea626700 (LWP 28934)]
[New Thread 0x7fffe9e25700 (LWP 28935)]
[New Thread 0x7fffe9407700 (LWP 28936)]
[New Thread 0x7fffe8c06700 (LWP 28937)]
[New Thread 0x7fffdbfff700 (LWP 28938)]
[New Thread 0x7fffdb7fe700 (LWP 28939)]
[New Thread 0x7fffdaffd700 (LWP 28941)]
[New Thread 0x7fffda7fc700 (LWP 28942)]
[Thread 0x7fffda7fc700 (LWP 28942) exited]
[Thread 0x7fffe9407700 (LWP 28936) exited]
[Thread 0x7fffdaffd700 (LWP 28941) exited]
[Thread 0x7fffe8c06700 (LWP 28937) exited]
[Thread 0x7fffdb7fe700 (LWP 28939) exited]
[New Thread 0x7fffdb7fe700 (LWP 29058)]
[New Thread 0x7fffdaffd700 (LWP 29059)]
[New Thread 0x7fffe8c06700 (LWP 29060)]
[New Thread 0x7fffe9407700 (LWP 29061)]
[New Thread 0x7fffda7fc700 (LWP 29062)]
[New Thread 0x7fffd9b8a700 (LWP 29063)]
[New Thread 0x7fffd9389700 (LWP 29064)]
[New Thread 0x7fffd8b88700 (LWP 29065)]
[New Thread 0x7fffb7fff700 (LWP 29067)]
[Thread 0x7fffe9407700 (LWP 29061) exited]
[Thread 0x7fffdbfff700 (LWP 28938) exited]
[Thread 0x7fffe8c06700 (LWP 29060) exited]
[Thread 0x7fffd8b88700 (LWP 29065) exited]
[Thread 0x7fffb7fff700 (LWP 29067) exited]
[Thread 0x7fffdb7fe700 (LWP 29058) exited]
[Thread 0x7fffda7fc700 (LWP 29062) exited]
[Thread 0x7fffd9389700 (LWP 29064) exited]
[Thread 0x7fffdaffd700 (LWP 29059) exited]

Program received signal SIGSEGV, Segmentation fault.
0x000000000044baa7 in wxWindowBase::Move (this=0x72726f742e295754, x=32, y=0, flags=0) at /usr/include/wx-2.8/wx/window.h:237
237         { DoSetSize(x, y, wxDefaultCoord, wxDefaultCoord, flags); }
```

**Comment by alberthdev** [comment] 2014-11-17 00:22
Thanks for the report, @SirCmpwn.

Interesting... unfortunately, I'm not able to reproduce this problem. Could you please attach a core dump AND the original binary you tried to run? Also, what OS (distro + version) and architecture did you build wxWabbitemu on?

Finally, could you run `wx-config --version` so I know what version of wxWidgets you are running? (From the output, it looks like you're using 2.8.x, but I'd like to ensure that's the case, and I'd like to know the exact version since some may be buggy.)

Thanks in advance!

**Comment by ddevault** [comment] 2014-11-17 07:12
I'm on Arch Linux, 64-bit.

[Core dump](http://irc.sircmpwn.com/dump)

[wxWabbitemu binary](http://irc.sircmpwn.com/wxWabbitemu)

[ROM file](http://irc.sircmpwn.com/KnightOS-TI84pSE.rom)

I'm using wx 3.0.2.

**Comment by alberthdev** [comment] 2014-11-20 05:50
Thanks for the files!

I was unable to reproduce your exact bug, but I was able to get something very similar (if not the same). The steps to trigger this were... interesting. (See commit message in the branch below for the way I was able to trigger this bug.)

Could you try checking out the branch `fix/onresize-race-condition` and building from source there? It's a bit of a dirty fix, but I think it'll work.

If the bug triggers again, instead of crashing, you should see this instead:

```
$ ./wxWabbitemu
WARNING: this->isShownVar == 1 returned false - NOT moving.
WARNING: this->isShownVar == 1 returned false - NOT moving.
```

Let me know if you're now seeing this message. On rarer occasions, you may even see this:

```
WARNING: wxLCD->IsShown() returned false - NOT moving.
```

Let me know if you see this at all.

If you don't mind, could you stay on this issue to produce a better core-dump and/or backtrace? I'm thinking about reporting this issue to wxWidgets, just in case this does happen to be their bug.

For reference, this is the bug on my side of things:

```
(gdb) run
Starting program: /home/albert/wxWabbitemu/wxwabbitemu/bin/wxWabbitemu 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed43c700 (LWP 28991)]
[New Thread 0x7fffecc3b700 (LWP 28992)]
[New Thread 0x7fffe5d46700 (LWP 28993)]
[New Thread 0x7fffe5545700 (LWP 28994)]
[New Thread 0x7fffdadf8700 (LWP 28995)]
[New Thread 0x7fffda5f7700 (LWP 28996)]
[Thread 0x7fffe5545700 (LWP 28994) exited]
[Thread 0x7fffdadf8700 (LWP 28995) exited]
[Thread 0x7fffe5d46700 (LWP 28993) exited]
[New Thread 0x7fffe5d46700 (LWP 29003)]
[New Thread 0x7fffdadf8700 (LWP 29004)]
[New Thread 0x7fffe5545700 (LWP 29005)]
[New Thread 0x7fffd8ae2700 (LWP 29006)]
[New Thread 0x7fffcbfff700 (LWP 29007)]
[New Thread 0x7fffcb7fe700 (LWP 29008)]
[New Thread 0x7fffcaffd700 (LWP 29009)]
[New Thread 0x7fffca7fc700 (LWP 29010)]
[New Thread 0x7fffc9ffb700 (LWP 29011)]
[Thread 0x7fffe5545700 (LWP 29005) exited]
[Thread 0x7fffe5d46700 (LWP 29003) exited]
[Thread 0x7fffdadf8700 (LWP 29004) exited]
[Thread 0x7fffcb7fe700 (LWP 29008) exited]
[Thread 0x7fffcaffd700 (LWP 29009) exited]
[Thread 0x7fffc9ffb700 (LWP 29011) exited]
[Thread 0x7fffca7fc700 (LWP 29010) exited]
[Thread 0x7fffcbfff700 (LWP 29007) exited]
[Thread 0x7fffda5f7700 (LWP 28996) exited]

Program received signal SIGSEGV, Segmentation fault.
0x000000000044bb3d in wxWindowBase::Move (this=0xff8d8d8dff8d8d8d, x=32, y=0, flags=0) at /usr/include/wx-2.8/wx/window.h:237
237         { DoSetSize(x, y, wxDefaultCoord, wxDefaultCoord, flags); }
(gdb) bt
#0  0x000000000044bb3d in wxWindowBase::Move (this=0xff8d8d8dff8d8d8d, x=32, y=0, flags=0) at /usr/include/wx-2.8/wx/window.h:237
#1  0x0000000000448508 in WabbitemuFrame::OnResize (this=0x16d3a70, event=...) at ../gui/gui.cpp:535
#2  0x00007ffff707e966 in wxEvtHandler::ProcessEventIfMatches(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#3  0x00007ffff707ea0b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#4  0x00007ffff707ed77 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#5  0x00007ffff77416db in wxFrame::GtkOnSize() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-2.8.so.0
#6  0x00007ffff76fc75c in wxTopLevelWindowGTK::Show(bool) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-2.8.so.0
#7  0x00000000004447fd in gui_frame (lpCalc=0x858bc0 <calcs>) at ../gui/gui.cpp:160
#8  0x000000000045a804 in RomWizard::OnFinish (this=0x7fffffffdc00, event=...) at ../gui/wizard/romwizard.cpp:177
#9  0x00007ffff707e966 in wxEvtHandler::ProcessEventIfMatches(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#10 0x00007ffff707ea0b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#11 0x00007ffff707ed77 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#12 0x00007ffff7ba5675 in wxWizard::ShowPage(wxWizardPage*, bool) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_adv-2.8.so.0
#13 0x00007ffff707e966 in wxEvtHandler::ProcessEventIfMatches(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#14 0x00007ffff707ea0b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#15 0x00007ffff707ed77 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#16 0x00007ffff77d1ef9 in wxWindowBase::TryParent(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-2.8.so.0
#17 0x00007ffff77306ec in ?? () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-2.8.so.0
#18 0x00007ffff57565e7 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff576f088 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff576fce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff5ef6585 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#22 0x00007ffff57565e7 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff576f088 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff576fce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff5ef54d9 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#26 0x00007ffff5f97815 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#27 0x00007ffff57563b8 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff5767afb in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff576f6f9 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007ffff576fce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff60a7724 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#32 0x00007ffff5f95fc4 in gtk_propagate_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#33 0x00007ffff5f9637b in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#34 0x00007ffff5c111ec in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#35 0x00007ffff5486e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff5487048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff548730a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff5f95447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#39 0x00007ffff76f428a in wxEventLoop::Run() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-2.8.so.0
#40 0x00007ffff773b6d0 in wxDialog::ShowModal() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-2.8.so.0
#41 0x00007ffff7ba5818 in wxWizard::RunWizard(wxWizardPage*) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_adv-2.8.so.0
#42 0x0000000000459d15 in RomWizard::Begin (this=0x7fffffffdc00) at ../gui/wizard/romwizard.cpp:29
#43 0x000000000044cca0 in WabbitemuApp::DoRomWizard () at ../gui/guiapp.cpp:10
#44 0x000000000044d0f2 in WabbitemuApp::OnInit (this=0x1341080) at ../gui/guiapp.cpp:51
#45 0x000000000044dcab in wxAppConsole::CallOnInit (this=0x1341080) at /usr/include/wx-2.8/wx/app.h:76
#46 0x00007ffff702be4c in wxEntry(int&, wchar_t**) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#47 0x000000000044460b in main (argc=1, argv=0x7fffffffe118) at ../gui/gui.cpp:119
(gdb) break ../gui/gui.cpp:535
Breakpoint 1 at 0x4484a9: file ../gui/gui.cpp, line 535.
(gdb) restart
Requires argument (checkpoint id to restart)
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/albert/wxWabbitemu/wxwabbitemu/bin/wxWabbitemu 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed43c700 (LWP 1340)]
[New Thread 0x7fffecc3b700 (LWP 1341)]
[New Thread 0x7fffe5d46700 (LWP 1345)]
[New Thread 0x7fffe5545700 (LWP 1346)]
[New Thread 0x7fffdadf8700 (LWP 1347)]
[New Thread 0x7fffda5f7700 (LWP 1348)]
[New Thread 0x7fffd9df6700 (LWP 1349)]
[Thread 0x7fffe5d46700 (LWP 1345) exited]
[Thread 0x7fffda5f7700 (LWP 1348) exited]
[Thread 0x7fffe5545700 (LWP 1346) exited]
[Thread 0x7fffdadf8700 (LWP 1347) exited]
[New Thread 0x7fffdadf8700 (LWP 1357)]
[New Thread 0x7fffe5545700 (LWP 1358)]
[New Thread 0x7fffda5f7700 (LWP 1359)]
[New Thread 0x7fffe5d46700 (LWP 1360)]
[New Thread 0x7fffc3fff700 (LWP 1361)]
[New Thread 0x7fffc37fe700 (LWP 1362)]
[New Thread 0x7fffc2ffd700 (LWP 1363)]
[New Thread 0x7fffc27fc700 (LWP 1364)]
[New Thread 0x7fffc1ffb700 (LWP 1365)]
[Thread 0x7fffe5545700 (LWP 1358) exited]
[Thread 0x7fffc1ffb700 (LWP 1365) exited]
[Thread 0x7fffda5f7700 (LWP 1359) exited]
[Thread 0x7fffc2ffd700 (LWP 1363) exited]
[Thread 0x7fffd9df6700 (LWP 1349) exited]
[Thread 0x7fffe5d46700 (LWP 1360) exited]
[Thread 0x7fffc27fc700 (LWP 1364) exited]
[Thread 0x7fffc37fe700 (LWP 1362) exited]
[Thread 0x7fffc3fff700 (LWP 1361) exited]

Breakpoint 1, WabbitemuFrame::OnResize (this=0x16de960, event=...) at ../gui/gui.cpp:535
535         wxLCD->Move((GetClientSize().GetWidth() - lpCalc->cpu.pio.lcd->width * scale) / 2, 0);
(gdb) step
[Thread 0x7fffdadf8700 (LWP 1357) exited]
wxWindowBase::GetClientSize (this=0x16de960) at /usr/include/wx-2.8/wx/window.h:294
294         DoGetClientSize(&w, &h);
(gdb) step
296         return wxSize(w, h);
(gdb) step
wxSize::wxSize (this=0x7fffffffc510, xx=256, yy=82) at /usr/include/wx-2.8/wx/gdicmn.h:215
215     wxSize(int xx, int yy) : x(xx), y(yy) { }
(gdb) step
wxWindowBase::GetClientSize (this=0x16de960) at /usr/include/wx-2.8/wx/window.h:297
297     }
(gdb) step
wxSize::GetWidth (this=0x7fffffffc560) at /usr/include/wx-2.8/wx/gdicmn.h:254
254     int GetWidth() const { return x; }
(gdb) step
wxWindowBase::Move (this=0x14b6d00, x=32, y=0, flags=0) at /usr/include/wx-2.8/wx/window.h:237
237         { DoSetSize(x, y, wxDefaultCoord, wxDefaultCoord, flags); }
(gdb) step

Program received signal SIGSEGV, Segmentation fault.
0x000000000044bb64 in wxWindowBase::Move (this=0x14b6d00, x=32, y=0, flags=0) at /usr/include/wx-2.8/wx/window.h:237
237         { DoSetSize(x, y, wxDefaultCoord, wxDefaultCoord, flags); }
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/albert/wxWabbitemu/wxwabbitemu/bin/wxWabbitemu 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed43c700 (LWP 2395)]
[New Thread 0x7fffecc3b700 (LWP 2399)]
[New Thread 0x7fffe5d46700 (LWP 2400)]
[New Thread 0x7fffe5545700 (LWP 2401)]
[New Thread 0x7fffdadf8700 (LWP 2402)]
[New Thread 0x7fffda5f7700 (LWP 2403)]
[New Thread 0x7fffd9df6700 (LWP 2407)]
[Thread 0x7fffda5f7700 (LWP 2403) exited]
[Thread 0x7fffe5545700 (LWP 2401) exited]
[Thread 0x7fffd9df6700 (LWP 2407) exited]
[Thread 0x7fffdadf8700 (LWP 2402) exited]
[New Thread 0x7fffdadf8700 (LWP 2427)]
[New Thread 0x7fffd9df6700 (LWP 2431)]
[New Thread 0x7fffe5545700 (LWP 2432)]
[New Thread 0x7fffda5f7700 (LWP 2433)]
[New Thread 0x7fffc3fff700 (LWP 2434)]
[New Thread 0x7fffc37fe700 (LWP 2436)]
[New Thread 0x7fffc2ffd700 (LWP 2437)]
[New Thread 0x7fffc27fc700 (LWP 2451)]
[New Thread 0x7fffc1ffb700 (LWP 2453)]
[Thread 0x7fffc37fe700 (LWP 2436) exited]
[Thread 0x7fffc2ffd700 (LWP 2437) exited]
[Thread 0x7fffc1ffb700 (LWP 2453) exited]
[Thread 0x7fffc3fff700 (LWP 2434) exited]
[Thread 0x7fffd9df6700 (LWP 2431) exited]
[Thread 0x7fffe5d46700 (LWP 2400) exited]
[Thread 0x7fffc27fc700 (LWP 2451) exited]
[Thread 0x7fffdadf8700 (LWP 2427) exited]
[Thread 0x7fffe5545700 (LWP 2432) exited]
[New Thread 0x7fffe5545700 (LWP 2482)]
[Thread 0x7fffda5f7700 (LWP 2433) exited]
[Thread 0x7fffe5545700 (LWP 2482) exited]
[Thread 0x7fffecc3b700 (LWP 2399) exited]
[Thread 0x7fffed43c700 (LWP 2395) exited]
[Inferior 1 (process 2387) exited normally]
(gdb) run
Starting program: /home/albert/wxWabbitemu/wxwabbitemu/bin/wxWabbitemu 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed43c700 (LWP 2516)]
[New Thread 0x7fffecc3b700 (LWP 2517)]
[New Thread 0x7fffe5d46700 (LWP 2518)]
[New Thread 0x7fffe5545700 (LWP 2519)]
[New Thread 0x7fffdadf8700 (LWP 2520)]
[New Thread 0x7fffda5f7700 (LWP 2521)]
[New Thread 0x7fffd9df6700 (LWP 2522)]
[New Thread 0x7fffd95f5700 (LWP 2523)]
[Thread 0x7fffd95f5700 (LWP 2523) exited]
[Thread 0x7fffdadf8700 (LWP 2520) exited]
[Thread 0x7fffda5f7700 (LWP 2521) exited]
[Thread 0x7fffe5d46700 (LWP 2518) exited]
[Thread 0x7fffe5545700 (LWP 2519) exited]
[New Thread 0x7fffe5545700 (LWP 2531)]
[New Thread 0x7fffe5d46700 (LWP 2532)]
[Thread 0x7fffe5545700 (LWP 2531) exited]
[Thread 0x7fffd9df6700 (LWP 2522) exited]

Breakpoint 1, WabbitemuFrame::OnResize (this=0x16acd40, event=...) at ../gui/gui.cpp:535
535         wxLCD->Move((GetClientSize().GetWidth() - lpCalc->cpu.pio.lcd->width * scale) / 2, 0);
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/albert/wxWabbitemu/wxwabbitemu/bin/wxWabbitemu 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed43c700 (LWP 2802)]
[New Thread 0x7fffecc3b700 (LWP 2804)]
[New Thread 0x7fffe5d46700 (LWP 2805)]
[New Thread 0x7fffe5545700 (LWP 2806)]
[New Thread 0x7fffe4d44700 (LWP 2807)]
[New Thread 0x7fffda857700 (LWP 2808)]
[New Thread 0x7fffda056700 (LWP 2809)]
[Thread 0x7fffda857700 (LWP 2808) exited]
[Thread 0x7fffe5545700 (LWP 2806) exited]
[Thread 0x7fffe4d44700 (LWP 2807) exited]
[Thread 0x7fffe5d46700 (LWP 2805) exited]
[New Thread 0x7fffe5d46700 (LWP 2817)]
[New Thread 0x7fffe4d44700 (LWP 2818)]
[New Thread 0x7fffe5545700 (LWP 2819)]
[New Thread 0x7fffda857700 (LWP 2820)]
[New Thread 0x7fffc3fff700 (LWP 2821)]
[New Thread 0x7fffc37fe700 (LWP 2822)]
[New Thread 0x7fffc2ffd700 (LWP 2823)]
[New Thread 0x7fffc27fc700 (LWP 2824)]
[New Thread 0x7fffc1ffb700 (LWP 2825)]
[Thread 0x7fffc3fff700 (LWP 2821) exited]
[Thread 0x7fffe5d46700 (LWP 2817) exited]
[Thread 0x7fffc27fc700 (LWP 2824) exited]
[Thread 0x7fffe5545700 (LWP 2819) exited]
[Thread 0x7fffc37fe700 (LWP 2822) exited]
[Thread 0x7fffc2ffd700 (LWP 2823) exited]
[Thread 0x7fffda056700 (LWP 2809) exited]
[Thread 0x7fffe4d44700 (LWP 2818) exited]
[Thread 0x7fffda857700 (LWP 2820) exited]

Breakpoint 1, WabbitemuFrame::OnResize (this=0x16d6050, event=...) at ../gui/gui.cpp:535
535         if (wxLCD->IsShown()) {
(gdb) step
wxWindowBase::GetClientSize (this=0x16d6050) at /usr/include/wx-2.8/wx/window.h:294
294         DoGetClientSize(&w, &h);
(gdb) step
296         return wxSize(w, h);
(gdb) step
wxSize::wxSize (this=0x7fffffffc510, xx=256, yy=82) at /usr/include/wx-2.8/wx/gdicmn.h:215
215     wxSize(int xx, int yy) : x(xx), y(yy) { }
(gdb) step
wxWindowBase::GetClientSize (this=0x16d6050) at /usr/include/wx-2.8/wx/window.h:297
297     }
(gdb) step
wxSize::GetWidth (this=0x7fffffffc560) at /usr/include/wx-2.8/wx/gdicmn.h:254
254     int GetWidth() const { return x; }
(gdb) step
[Thread 0x7fffc1ffb700 (LWP 2825) exited]
wxWindowBase::Move (this=0x16e6110, x=32, y=0, flags=0) at /usr/include/wx-2.8/wx/window.h:237
237         { DoSetSize(x, y, wxDefaultCoord, wxDefaultCoord, flags); }
(gdb) step

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) quit
A debugging session is active.

    Inferior 1 [process 2800] will be killed.

Quit anyway? (y or n) y
```

**Comment by alberthdev** [comment] 2017-03-24 01:31
Closing issue since this seems to work! (This fix is now present in master.) If this is still broken and/or prone to crashes, feel free to re-open this issue!

**Closed as completed by alberthdev** 2017-03-24 01:31 UTC
